language: python
sudo: false

python:
   - "2.7"
   - "3.6"

env:
  global:
    # Doctr deploy key for deGrootLab/pmx
    - secure: "uckmVtg2suI5F7M+OZnFnnx8hbyA4SScT7rrXKmi8CnOaXg5on+4mRxNf/WD8hTqG/tLKj5RdE5Y4i3Wt7Gg8hDynSCyMJlvWR5Sz/ecKfzp+ZzMECbIZdynrLniGidWYtBgHlktruDHyGpGDz5AWR9sG8ozJYdTUZUniFOK5dW5AtxrltfipQJmzAITI0RkN16Nm6J+i+DWkiwa+E4ejEn9j7lkznzNvMF1PCoQhNu6ur2BxSnJar/3d5jOWFVLORBVLsMDg29qiWCpTnt4bi27bZz/6cvy9Pdc2WpHkNeTnQk6iCbwF1Eu5kf3OFaESnnHzOruME0FiLeOd/XJdSfAbWA1up8wE6LxihoEGtkNhqbmiMzA1EQZGboQwKL8Jx0YCsrW30PIKWEDEIetOxsk9KIidt/erpaKFWt8X4t3nMvvft0rYs3hG7OdnqQ49cSEgn5ZoN9KSw/bvptkTLj6yxPuwrtmVs/35CpcD4qjCHwLpQ4FRvxMRoXf2Igy8/9PBS2VeVOVGV+cKB3dPp8B8025yXdGjJGgw30vfbuuUN9wStXyHb0xPgw466fVc20r9wZ9/zNTiJSNX/aNEo8fF6/r0HoNOmLIjEpKEOSw/zjoYiw8UXVMEZmxARuM6izN21taAt6RuvUaB8Nsa/CxD369cIb8uBt2D3zFYpY="

branches:
    only:
        - develop

install:
    - pip install --upgrade pip setuptools wheel
    - pip install --upgrade pytest
    - pip install codecov
    - pip install pytest-cov
    - pip install -e .

script:
    - py.test --cov pmx tests/
    - |
      if [[ $TRAVIS_PYTHON_VERSION == "3.6" ]]; then
        set -e
        pip install doctr
        pip install sphinx sphinx_rtd_theme msmb_theme
        cd docs
        make html
        cd ../
        doctr deploy . --built-docs docs/build/html/ --no-require-master --branch-whitelist develop
      fi

after_success:
    - codecov
